# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LE.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LengthEdit(object):
    def setupUi(self, LengthEdit):
        LengthEdit.setObjectName("LengthEdit")
        LengthEdit.resize(346, 151)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LengthEdit.sizePolicy().hasHeightForWidth())
        LengthEdit.setSizePolicy(sizePolicy)
        LengthEdit.setStyleSheet("background-image: url(:/bg/woods2.jpg);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(LengthEdit)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 90, 241, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acceptButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.acceptButton.setFont(font)
        self.acceptButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(190, 167, 31, 77), stop:1 rgba(255, 255, 218, 89));")
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout.addWidget(self.acceptButton)
        self.rejectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.rejectButton.setFont(font)
        self.rejectButton.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(190, 167, 31, 77), stop:1 rgba(255, 255, 218, 89));")
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout.addWidget(self.rejectButton)
        self.label = QtWidgets.QLabel(LengthEdit)
        self.label.setGeometry(QtCore.QRect(50, 55, 120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(LengthEdit)
        self.comboBox.setGeometry(QtCore.QRect(190, 55, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(LengthEdit)
        self.label_2.setGeometry(QtCore.QRect(50, 15, 120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.timeBox = QtWidgets.QComboBox(LengthEdit)
        self.timeBox.setGeometry(QtCore.QRect(190, 15, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.timeBox.setFont(font)
        self.timeBox.setObjectName("timeBox")
        self.timeBox.addItem("")
        self.timeBox.addItem("")
        self.timeBox.addItem("")
        self.timeBox.addItem("")

        self.retranslateUi(LengthEdit)
        QtCore.QMetaObject.connectSlotsByName(LengthEdit)

    def retranslateUi(self, LengthEdit):
        _translate = QtCore.QCoreApplication.translate
        LengthEdit.setWindowTitle(_translate("LengthEdit", "等待开始"))
        self.acceptButton.setText(_translate("LengthEdit", "确认"))
        self.rejectButton.setText(_translate("LengthEdit", "退出"))
        self.label.setText(_translate("LengthEdit", "选择棋盘大小"))
        self.comboBox.setItemText(0, _translate("LengthEdit", "10*10"))
        self.comboBox.setItemText(1, _translate("LengthEdit", "16*16"))
        self.comboBox.setItemText(2, _translate("LengthEdit", "20*20"))
        self.comboBox.setItemText(3, _translate("LengthEdit", "24*24"))
        self.label_2.setText(_translate("LengthEdit", "选择时间限制"))
        self.timeBox.setItemText(0, _translate("LengthEdit", "不限"))
        self.timeBox.setItemText(1, _translate("LengthEdit", "15"))
        self.timeBox.setItemText(2, _translate("LengthEdit", "30"))
        self.timeBox.setItemText(3, _translate("LengthEdit", "45"))

import src.scc_rc
